<a href="https://colab.research.google.com/github/19PA1A02A1/AI--lab/blob/master/EXPERIMENT_1_1_NUMPY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
EXPERIMENT-1 1.NUMPY

i) Different ways to create NumPy arrays

In [1]:
import numpy as np
a=np.array([4,5,6])
print(a)

[4 5 6]


In [2]:
a=np.array([[11,12],[13,14]])
print(a)

[[11 12]
 [13 14]]


ii) Add, remove, modify elements in an array.

In [3]:
newArray = np.append(a,[22,10,36])
print(newArray)

[11 12 13 14 22 10 36]


In [4]:
import numpy as np
l=np.array([5,10,4,3,1])
l=np.delete(l,4)
print(l)

[ 5 10  4  3]


In [5]:
b=np.array([8,5,4,1,3,7])
b[b<2]=-1
print(b)

[ 8  5  4 -1  3  7]


iii) Arithmetic operations on NumPy array

In [6]:
import numpy as np
v=np.random.random((3,3))
n=np.random.random((3,3))
sum=np.add(v,n)
diff=np.subtract(v,n)
prod=np.multiply(v,n)
quo=np.divide(v,n)
mod=np.mod(v,n)
pow=np.power(v,n)
print(sum)
print(diff)
print(prod)
print(quo)
print(mod)
print(pow)

[[1.02056093 1.42925801 0.42284601]
 [0.96266966 0.19933528 1.7089314 ]
 [0.31731747 0.65806742 1.02295557]]
[[-0.93046947 -0.2053283   0.10134263]
 [-0.02147519  0.05483942 -0.02376405]
 [-0.07368908 -0.2439553   0.01429999]]
[[0.04394279 0.50015468 0.0421321 ]
 [0.23156792 0.0091818  0.72997045]
 [0.02381507 0.09338464 0.2615584 ]]
[[0.04617634 0.74877032 1.63042961]
 [0.95635767 1.75904491 0.97256985]
 [0.62308009 0.45909279 1.02835455]]
[[0.04504573 0.61196485 0.10134263]
 [0.47059724 0.05483942 0.84258368]
 [0.1218142  0.20705606 0.01429999]]
[[0.04859802 0.66941126 0.80633605]
 [0.69011232 0.86153564 0.8620948 ]
 [0.66259926 0.49152759 0.71811474]]


iv.Slicing and iterating of numpy arrays

slicing

In [7]:
import numpy as np
arr=np.array([2,4,6,8,9,3])
print(arr[2:6])

[6 8 9 3]


Iterating

In [9]:
for i in arr:
 print(i)

2
4
6
8
9
3


V) Matrix operations on NumPy arrays

In [10]:
import numpy as np
v=np.array([[3,6],[5,4]])
i=np.array([[5,25],[2,24]])
print(np.add(v,i))
print(np.subtract(v,i))
print(np.divide(v,i))

[[ 8 31]
 [ 7 28]]
[[ -2 -19]
 [  3 -20]]
[[0.6        0.24      ]
 [2.5        0.16666667]]
